// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO3GucxX9xL9waA4P_SrpUxOjUYWz3-Tw',
    appId: '1:71293995937:web:52c4560691ebdf525299e0',
    messagingSenderId: '71293995937',
    projectId: 'movies-f9765',
    authDomain: 'movies-f9765.firebaseapp.com',
    storageBucket: 'movies-f9765.appspot.com',
    measurementId: 'G-RY11CJTB2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIcyP8N8pgv6eRQI77DdEYvjRp-ss7-M8',
    appId: '1:71293995937:android:417f4a4e5fd4aa635299e0',
    messagingSenderId: '71293995937',
    projectId: 'movies-f9765',
    storageBucket: 'movies-f9765.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe9-IfLpMhNzJeg9f0ebGuhwU0A1tUl7A',
    appId: '1:71293995937:ios:199a759b79fc5fd65299e0',
    messagingSenderId: '71293995937',
    projectId: 'movies-f9765',
    storageBucket: 'movies-f9765.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe9-IfLpMhNzJeg9f0ebGuhwU0A1tUl7A',
    appId: '1:71293995937:ios:199a759b79fc5fd65299e0',
    messagingSenderId: '71293995937',
    projectId: 'movies-f9765',
    storageBucket: 'movies-f9765.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );
}
